config/routes.rb
Rails.application.routes.draw do
  LOCALES = /en|pt\-BR/

  scope "(:locale)", locale: LOCALES do
    get 'home/index'

    resources :home_categories
    resources :herba_categories

    resources :home_clients
    resources :herba_clients

    resources :herba_incomes
    resources :herba_items do
      member do
        post "confirm_delivery"
      end
    end

    resources :herba_products do
      member do
        post "add_item"
      end
    end

    resources :herba_profiles

    resources :herba_titles

    resources :home_transactions do
      collection do
        get "new_credit_card"
        post "create_credit_card"
        get "new_transfer"
        post "create_transfer"
      end
    end

    resources :herba_transactions

    if Rails.env.production?
      devise_for :users, :controllers => { :registrations => "registrations" } 
    else
      devise_for :users
    end
  end

  get "/:locale" => "home#index", locale: LOCALES
  root to: "home#index"

end

app/models/herba_client.rb
class HerbaClient < ActiveRecord::Base
	EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

	validates_presence_of :name
	validates_format_of :email, with: EMAIL_REGEXP

	belongs_to :herba_title

	has_one :herba_address
	has_many :herba_items
	has_many :herba_incomes
	has_many :herba_profiles
	has_many :herba_transactions


	accepts_nested_attributes_for :herba_address

	before_create :set_initial_title

	def balance
		self.herba_transactions.credits.sum(:value) - self.herba_transactions.debits.sum(:value)
	end

	def payment_balance
		self.herba_items.not_payment.sum(:price) - balance
	end

	def client_credits
		total = 0
		HerbaClient.where("id > ?", 1).collect { |c| total += c.balance }
		total
	end

	def status?
		items = self.herba_items.where("date(product_date) >= ?", Date.today)
		items.present? ? true : false
	end

	def set_initial_base
		# HerbaClient.new.set_initial_base

		HerbaCategory.create(name: "Barra de Proteína")
		HerbaCategory.create(name: "Bebidas")
		HerbaCategory.create(name: "Outros")
		HerbaCategory.create(name: "Proteína")
		HerbaCategory.create(name: "Sachê")
		HerbaCategory.create(name: "Shakes")
		HerbaCategory.create(name: "Sopas")
		HerbaCategory.create(name: "Tabletes")

		HerbaProduct.create(code: "#0939", name: "Abacaxi com Hortelā", portion: 21, price: 112.0, herba_category_id: 6)
		HerbaProduct.create(code: "#0940", name: "Doce de Leite", portion: 21, price: 112.0, herba_category_id: 6)
		HerbaProduct.create(code: "#0952", name: "Chocolate Cremoso", portion: 21, price: 112.0, herba_category_id: 6)
		HerbaProduct.create(code: "#0146", name: "Cookies & Cream", portion: 21, price: 112.0, herba_category_id: 6)
		HerbaProduct.create(code: "#0951", name: "Baunilha Cremoso", portion: 21, price: 112.0, herba_category_id: 6)
		HerbaProduct.create(code: "#0946", name: "Mousse Maracujá", portion: 21, price: 112.0, herba_category_id: 6)
		HerbaProduct.create(code: "#0953", name: "Morango Cremoso", portion: 21, price: 112.0, herba_category_id: 6)
		HerbaProduct.create(code: "#0144", name: "Frutas Tropicais", portion: 21, price: 112.0, herba_category_id: 6)
		HerbaProduct.create(code: "#1199", name: "Chocolate com Coco", portion: 21, price: 112.0, herba_category_id: 6)
		HerbaProduct.create(code: "#8477", name: "Shakeira", portion: 1, price: 10.0, herba_category_id: 3)
		HerbaProduct.create(code: "#8848", name: "Braçadeira", portion: 1, price: 20.0, herba_category_id: 3)
		HerbaProduct.create(code: "#8639", name: "Pote Plástico", portion: 1, price: 3.0, herba_category_id: 3)
		HerbaProduct.create(code: "#0948", name: "Baunilha Cremoso", portion: 7, price: 40.0, herba_category_id: 5)
		HerbaProduct.create(code: "#0945", name: "Fiber Concentrate", portion: 15, price: 93.0, herba_category_id: 2)
		HerbaProduct.create(code: "#0242", name: "Pó de Proteína 240g", portion: 40, price: 101.0, herba_category_id: 4)
		HerbaProduct.create(code: "#0246", name: "Pó de Proteína 480g", portion: 80, price: 184.0, herba_category_id: 4)
		HerbaProduct.create(code: "#3114", name: "Fiber & Herb", portion: 30, price: 49.0, herba_category_id: 8)
		HerbaProduct.create(code: "#3122", name: "Multivitaminas e Minerais", portion: 45, price: 54.0, herba_category_id: 8)
		HerbaProduct.create(code: "#0130", name: "Fiberbond", portion: 30, price: 88.0, herba_category_id: 8)
		HerbaProduct.create(code: "#0020", name: "Xtra-Cal", portion: 60, price: 50.0, herba_category_id: 8)
		HerbaProduct.create(code: "#0065", name: "Herbalifeline", portion: 90, price: 129.0, herba_category_id: 8)
		HerbaProduct.create(code: "#0102", name: "NRG Pó", portion: 60, price: 74.0, herba_category_id: 2)
		HerbaProduct.create(code: "#0122", name: "NRG", portion: 30, price: 73.0, herba_category_id: 8)
		HerbaProduct.create(code: "#0255", name: "Limāo", portion: 29, price: 102.0, herba_category_id: 2)
		HerbaProduct.create(code: "#0257", name: "Pêssego", portion: 29, price: 102.0, herba_category_id: 2)
		HerbaProduct.create(code: "#0256", name: "Framboesa", portion: 29, price: 102.0, herba_category_id: 2)
		HerbaProduct.create(code: "#0105", name: "Original 50g", portion: 29, price: 102.0, herba_category_id: 2)
		HerbaProduct.create(code: "#0106", name: "Original 100g", portion: 59, price: 167.0, herba_category_id: 2)
		HerbaProduct.create(code: "#0030", name: "Brownie", portion: 7, price: 50.0, herba_category_id: 1)
		HerbaProduct.create(code: "#0031", name: "Citrus Lemon", portion: 7, price: 50.0, herba_category_id: 1)
		HerbaProduct.create(code: "#1052", name: "Frango com Legumes", portion: 7, price: 40.0, herba_category_id: 7)
		HerbaProduct.create(code: "#0554", name: "4 Queijos com Croutons", portion: 7, price: 40.0, herba_category_id: 7)
		HerbaProduct.create(code: "#1053", name: "Legumes e Verduras", portion: 7, price: 40.0, herba_category_id: 7)

		HerbaTitle.create(name: "Consumidor", discount: 0)
		HerbaTitle.create(name: "Consultor Independente", discount: 25)
		HerbaTitle.create(name: "Consultor Sênior", discount: 35)

		client = HerbaClient.create(name: "Edgard A. Mitani", email: "mitanix79@gmail.com", phone: "(43) 9926-3801")
    client.herba_address = HerbaAddress.new
    client.save
	end

	private
	def set_initial_title
		self[:herba_title_id] = 1
	end
end

app/controllers/herba_clients_controller.rb
class HerbaClientsController < ApplicationController
	before_action :authenticate_user!
	
  def index
    @clients = []
    if params[:client_name]
      @clients = HerbaClient.includes([:herba_title, :herba_items]).where("name like ?", "%#{params[:client_name]}%").order("name asc").page(params[:page])
      flash.now[:alert] = t("flash_message.client_not_found") if @clients.blank?
    else
      @clients = HerbaClient.includes([:herba_title, :herba_items]).order("name asc").page(params[:page])
    end
  end

  def edit
    @client = HerbaClient.find(params[:id])
  end

  def show
    @client = HerbaClient.includes(:herba_address).find(params[:id])
    session[:client_id] = @client.id
  end

  def new
    @client = HerbaClient.new
    @client.build_herba_address
    @client.build_herba_title
  end

  def create
    @client = HerbaClient.new(client_params)

    if @client.save
      redirect_to herba_clients_path, notice: t("title.client") + t("flash_message.successfully_created")
    else
      render action: :new
    end
  end

  def update
    @client = HerbaClient.find(params[:id])

    if @client.update(client_params)
      redirect_to herba_clients_path, notice: t("title.client") + t("flash_message.successfully_updated")
    else
      render action: :edit
    end
  end

  private
  def client_params
    params.require(:herba_client).permit(:herba_title_id, :name, :email, :phone, herba_address_attributes: [:id, :herba_client_id, :zip_code, :street, :number, :neighborhood, :city, :state])
  end
end

app/helpers/herba_clients_helper.rb
module HerbaClientsHelper
	def get_herba_titles
		HerbaTitle.all
	end

	def pending_item?(client)
		client.herba_items.not_payment.count > 0 ? true : false
	end
end

app/views/herba_clients/_address_fields.html.erb
<div class="box-header">
	<h3 class="box-title"><%= t("title.address") %></h3>
</div>
<div class="form-group">
	<div class="input-group">
		<div class="input-group-addon">
			<i class="fa fa-map-marker"></i>
		</div>
		<%= f.text_field :zip_code, class: "form-control", placeholder: t("placeholder.zip_code") %>
	</div>
</div>
<div class="form-group">
	<div class="input-group">
		<div class="input-group-addon">
			<i class="fa fa-map-marker"></i>
		</div>
		<%= f.text_field :street, class: "form-control", placeholder: t("placeholder.street") %>
	</div>
</div>
<div class="form-group">
	<div class="input-group">
		<div class="input-group-addon">
			<i class="fa fa-map-marker"></i>
		</div>
		<%= f.text_field :number, class: "form-control", placeholder: t("placeholder.number") %>
	</div>
</div>
<div class="form-group">
	<div class="input-group">
		<div class="input-group-addon">
			<i class="fa fa-map-marker"></i>
		</div>
		<%= f.text_field :neighborhood, class: "form-control", placeholder: t("placeholder.neighborhood") %>
	</div>
</div>
<div class="form-group">
	<div class="input-group">
		<div class="input-group-addon">
			<i class="fa fa-map-marker"></i>
		</div>
		<%= f.text_field :city, class: "form-control", placeholder: t("placeholder.city") %>
	</div>
</div>
<div class="form-group">
	<div class="input-group">
		<div class="input-group-addon">
			<i class="fa fa-map-marker"></i>
		</div>
		<%= f.text_field :state, class: "form-control", placeholder: t("placeholder.state") %>
	</div>
</div>

app/views/herba_clients/_form.html.erb
<% if @client.errors.any? %>
	<div id="error_explanation">
		<%= t("general.form_error") %>
	</div>
<% end %>

<section class="content">
	<div class="row">
		<div class="col-md-6">
			<div class="box box-primary">
				<div class="box-header">
					<h3 class="box-title"><%= t("title.client") %></h3>
				</div>
				<%= form_for @client do |f| %>
					<div class="box-body">
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-file-text-o"></i>
								</div>
								<%= f.text_field :name, class: "form-control", placeholder: t("placeholder.name") %>
								<%= error_tag @client, :name %>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-envelope"></i>
								</div>
								<%= f.text_field :email, class: "form-control", placeholder: t("placeholder.email") %>
								<%= error_tag @client, :email %>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-phone"></i>
								</div>
								<%= f.text_field :phone, class: "form-control", placeholder: t("placeholder.phone_example") %>
								<%= error_tag @client, :phone %>
							</div>
						</div>
						<%= f.fields_for :herba_address do |a| %>
							<%= render "address_fields", :f => a %>
						<% end %>
						<div class="box-header">
							<h3 class="box-title"><%= t("title.title") %></h3>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-caret-square-o-down"></i>
								</div>
								<%= f.select :herba_title_id, options_from_collection_for_select(get_herba_titles, "id", "name", @client.herba_title_id), {}, class: "form-control" %>
							</div>
						</div>
					</div>
					<div class="box-footer">
						<%= f.submit button_name, class: "btn btn-primary" %>
	        </div>
				<% end %>
			</div>
		</div>
	</div>
</section>

app/views/herba_clients/edit.html.erb
<%= render "form" %>

app/views/herba_clients/index.html.erb
<section class="content">
	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title"><%= t("title.clients") %></h3>
					<div class="box-tools">
						<%= link_to t("link.registering"), new_herba_client_path, class: "btn-register btn-default pull-right" %>
						<div class="input-group-table">
							<%= form_tag herba_clients_path, method: :get do %>
								<div class="input-group-btn-table">
	              	<%= button_tag "", class: "btn btn-sm btn-default" do %>
	              		<i class="fa fa-search"></i>
	              	<% end%>
	              </div>
								<%= text_field_tag :client_name, params[:client_name], class: "form-control input-sm pull-right", style: "width: 150px;", placeholder: t("placeholder.client_name") %>
								
							<% end %>
            </div>
					</div>
				</div>
				<div class="box-body table-responsive no-padding">
					<table class="table table-striped">
						<tr>
							<th><%= t("table.name") %></th>
							<th><%= t("table.email") %></th>
							<th><%= t("table.phone") %></th>
							<th><%= t("table.status") %></th>
							<th><%= t("table.to_receive") %></th>
							<th colspan="6"></th>
						</tr>
						<% @clients.each do |client| %>
							<% status = client.status? %>
							<tr>
								<td><%= link_to "", herba_products_path(client_id: client.id), class: "fa fa-shopping-cart", title: t("link.add_items") %> <%= link_to client.name, new_herba_transaction_path(client_id: client.id) %></td>
								<td><%= client.email %></td>
								<td><%= client.phone %></td>
								<td><font color=<%= status ? "green" : "red" %>><%= status ? "Ativo" : "Inativo" %></font></td>
								<td><%= format_money(client.payment_balance) if pending_item?(client) %></td>
								<td><%= link_to "", herba_profile_path(client), class: "fa fa-book", title: t("link.profile_list") %></td>
								<td><%= link_to "", herba_item_path(client), class: "fa fa-table", title: t("link.items_list") %></td>
								<td><%= link_to "", client, class: "fa fa-info", title: t("link.detail") %></td>
								<td><%= link_to "", edit_herba_client_path(client), class: "fa fa-edit", title: t("link.edit") %></td>
								<td><%= link_to "", client, method: :delete, data: { confirm: t("flash_message.are_you_sure") }, class: "fa fa-trash-o", title: t("link.delete") %></td>
							</tr>
						<% end %>
					</table>
					<div class="box-footer clearfix">
						<div class="pagination pagination-sm no-margin pull-right">
							<%= will_paginate @clients if @clients.present? %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/herba_clients/new.html.erb
<%= render "form" %>

app/views/herba_clients/show.html.erb
<section class="content">
	<div class="row">
		<div class="col-md-6">
			<div class="box box-primary">
				<div class="box-header">
					<h3 class="box-title"><%= t("title.client") %></h3>
				</div>
				<div class="box-body">
					<div class="form-group">
						<div class="input-group">
							<div class="input-group-addon">
								<i class="fa fa-file-text-o"></i>
							</div>
							<%= text_field_tag :name, @client.name, class: "form-control", disabled: true %>
						</div>
					</div>
					<div class="form-group">
						<div class="input-group">
							<div class="input-group-addon">
								<i class="fa fa-envelope"></i>
							</div>
							<%= text_field_tag :email, @client.email, class: "form-control", disabled: true %>
						</div>
					</div>
					<div class="form-group">
						<div class="input-group">
							<div class="input-group-addon">
								<i class="fa fa-phone"></i>
							</div>
							<%= text_field_tag :phone, @client.phone, class: "form-control", disabled: true %>
						</div>
					</div>
					<% if @client.herba_address %>
						<div class="box-header">
							<h3 class="box-title"><%= t("title.address") %></h3>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-map-marker"></i>
								</div>
								<%= text_field_tag :zip_code, @client.herba_address.zip_code, class: "form-control", disabled: true %>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-map-marker"></i>
								</div>
								<%= text_field_tag :street, @client.herba_address.street, class: "form-control", disabled: true %>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-map-marker"></i>
								</div>
								<%= text_field_tag :number, @client.herba_address.number, class: "form-control", disabled: true %>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-map-marker"></i>
								</div>
								<%= text_field_tag :neighborhood, @client.herba_address.neighborhood, class: "form-control", disabled: true %>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-map-marker"></i>
								</div>
								<%= text_field_tag :city, @client.herba_address.city, class: "form-control", disabled: true %>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-map-marker"></i>
								</div>
								<%= text_field_tag :state, @client.herba_address.state, class: "form-control", disabled: true %>
							</div>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</section>