config/routes.rb
Rails.application.routes.draw do
  LOCALES = /en|pt\-BR/

  scope "(:locale)", locale: LOCALES do
    get 'home/index'

    resources :home_categories
    resources :herba_categories

    resources :home_clients
    resources :herba_clients

    resources :herba_incomes
    resources :herba_items do
      member do
        post "confirm_delivery"
      end
    end

    resources :herba_products do
      member do
        post "add_item"
      end
    end

    resources :herba_profiles

    resources :herba_titles

    resources :home_transactions do
      collection do
        get "new_credit_card"
        post "create_credit_card"
        get "new_transfer"
        post "create_transfer"
      end
    end

    resources :herba_transactions

    if Rails.env.production?
      devise_for :users, :controllers => { :registrations => "registrations" } 
    else
      devise_for :users
    end
  end

  get "/:locale" => "home#index", locale: LOCALES
  root to: "home#index"

end

app/models/herba_product.rb
class HerbaProduct < ActiveRecord::Base
	validates_presence_of :herba_category_id, :code, :name, :price, :portion
	validates_uniqueness_of :code

	has_many :herba_items
	belongs_to :herba_category

	def add_item(client_id, product)
		profit = product.price * (HerbaClient.first.herba_title.discount/100)
    HerbaItem.create(herba_client_id: client_id, herba_product_id: product.id, price: product.price, profit: profit)
	end
end

app/controllers/herba_products_controller.rb
class HerbaProductsController < ApplicationController
	before_action :authenticate_user!
  
  def index
    if params[:category_id].present?
      @products = HerbaProduct.where(herba_category_id: params[:category_id]).order(:name)
    else
      @products = HerbaProduct.includes(:herba_category).all.order(:name)
    end
    session[:client_id] = params[:client_id] if params[:client_id]
    @client = HerbaClient.find(session[:client_id])
  end

  def edit
    @product = HerbaProduct.find(params[:id])
  end

  def new
    @product = HerbaProduct.new
    @categories = HerbaCategory.all.order(:name)
  end

  def show
  end

  def create
    @product = HerbaProduct.new(product_params)

    if @product.save
      redirect_to herba_products_path, notice: t("title.product") + t("flash_message.successfully_created")
    else
      render action: :new
    end
  end

  def update
    @product = HerbaProduct.find(params[:id])

    if @product.update(product_params)
      redirect_to herba_products_path, notice: t("title.product") + t("flash_message.successfully_updated")
    else
      render action: :edit
    end
  end

  def add_item
    product = HerbaProduct.find(params[:id])
    product.add_item(session[:client_id], product)
    redirect_to herba_products_path, notice: t("title.product") + t("flash_message.successfully_added")
  end

  private
  def product_params
    params.require(:herba_product).permit(:herba_category_id, :code, :name, :price, :portion)
  end
end

app/helpers/herba_products_helper.rb
module HerbaProductsHelper
	def get_herba_categories
		HerbaCategory.all
	end
end

app/views/herba_products/_form.html.erb
<% if @product.errors.any? %>
	<div id="error_explanation">
		<%= t("general.form_error") %>
	</div>
<% end %>

<section class="content">
	<div class="row">
		<div class="col-md-6">
			<div class="box box-primary">
				<div class="box-header">
					<h3 class="box-title"><%= t("title.product") %></h3>
				</div>
				<%= form_for @product do |f| %>
					<div class="box-body">
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-caret-square-o-down"></i>
								</div>
								<%= f.select :herba_category_id, options_from_collection_for_select(get_herba_categories, "id", "name", @product.herba_category_id), {}, class: "form-control" %>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-file-text-o"></i>
								</div>
								<%= f.text_field :code, class: "form-control", placeholder: t("placeholder.code") %>
								<%= error_tag @product, :code %>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-file-text-o"></i>
								</div>
								<%= f.text_field :name, class: "form-control", placeholder: t("placeholder.name") %>
								<%= error_tag @product, :name %>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-money"></i>
								</div>
								<%= f.text_field :price, class: "form-control", placeholder: t("placeholder.money_example") %>
								<%= error_tag @product, :price %>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-retweet"></i>
								</div>
								<%= f.text_field :portion, class: "form-control", placeholder: t("placeholder.portion") %>
								<%= error_tag @product, :portion %>
							</div>
						</div>
					</div>
					<div class="box-footer">
						<%= f.submit button_name, class: "btn btn-primary" %>
	        </div>
				<% end %>
			</div>
		</div>
	</div>
</section>

app/views/herba_products/edit.html.erb
<%= render "form" %>

app/views/herba_products/index.html.erb
<section class="content">
	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title"><%= t("title.products") %></h3>
					<div class="box-tools">
						<%= link_to t("link.registering"), new_herba_product_path, class: "btn-register btn-default pull-right" %>
						<div class="input-group-table">
							<%= form_tag herba_products_path, method: :get do %>
								<div class="input-group-btn-table">
	              	<%= button_tag "", class: "btn btn-sm btn-default" do %>
	              		<i class="fa fa-search"></i>
	              	<% end%>
	              </div>
								<%= select_tag :herba_category_id, options_from_collection_for_select(get_herba_categories, "id", "name", params[:category_id]), :include_blank => true, class: "form-control-table pull-right" %>
							<% end %>
            </div>
					</div>
				</div>
				<div class="box-body table-responsive no-padding">
					<table class="table table-striped">
						<tr>
							<th>ID</th>
							<th><%= t("table.name") %></th>
							<th><%= t("table.category") %></th>
							<th><%= t("table.portion") %></th>
							<th><%= t("table.price") %></th>
							<th colspan="3"></th>
						</tr>
						<% @products.each do |product| %>
							<tr>
								<td><%= product.code %></td>
								<td><%= link_to "", add_item_herba_product_path(product), method: :post, data: { confirm: t("flash_message.are_you_sure") }, class: "fa fa-shopping-cart", title: t("link.add") if session[:client_id] %> <%= product.name %></td>
								<td><%= product.herba_category.name %></td>
								<td><%= product.portion %></td>
								<td><%= format_money(product.price) %></td>
								<td><%= link_to "", edit_herba_product_path(product), class: "fa fa-edit", title: t("link.edit") %></td>
								<td><%= link_to "", product, method: :delete, data: { confirm: t("flash_message.are_you_sure") }, class: "fa fa-trash-o", title: t("link.delete") %></td>
							</tr>
						<% end %>
					</table>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/herba_products/new.html.erb
<%= render "form" %>