config/routes.rb
Rails.application.routes.draw do
  LOCALES = /en|pt\-BR/

  scope "(:locale)", locale: LOCALES do
    get 'home/index'

    resources :home_categories
    resources :herba_categories

    resources :home_clients
    resources :herba_clients

    resources :herba_incomes
    resources :herba_items do
      member do
        post "confirm_delivery"
      end
    end

    resources :herba_products do
      member do
        post "add_item"
      end
    end

    resources :herba_profiles

    resources :herba_titles

    resources :home_transactions do
      collection do
        get "new_credit_card"
        post "create_credit_card"
        get "new_transfer"
        post "create_transfer"
      end
    end

    resources :herba_transactions

    if Rails.env.production?
      devise_for :users, :controllers => { :registrations => "registrations" } 
    else
      devise_for :users
    end
  end

  get "/:locale" => "home#index", locale: LOCALES
  root to: "home#index"

end

app/models/home_category.rb
class HomeCategory < ActiveRecord::Base
	validates_presence_of :name
	validates_uniqueness_of :name

	has_many :home_transactions
end

app/controllers/home_categories_controller.rb
class HomeCategoriesController < ApplicationController
	before_action :authenticate_user!
	
  def index
    @categories = HomeCategory.all.order(:name)
  end

  def edit
  	@category = HomeCategory.find(params[:id])
  end

  def new
  	@category = HomeCategory.new
  end

  def create
  	@category = HomeCategory.new(category_params)

  	if @category.save
  		redirect_to home_categories_path, notice: t("title.category") + t("flash_message.successfully_created")
  	else
  		render action: :new
  	end
  end

  def update
  	@category = HomeCategory.find(params[:id])

  	if @category.update(category_params)
  		redirect_to home_categories_path, notice: t("title.category") + t("flash_message.successfully_updated")
  	else
  		render action: :edit
  	end
  end

  def destroy
    @category = HomeCategory.find(params[:id])
    @category.destroy

    redirect_to home_categories_path, notice: t("title.category") + t("flash_message.successfully_deleted")
  end

  private
  def category_params
  	params.require(:home_category).permit(:name)
  end
end

app/helpers/home_categories_helper.rb
module HomeCategoriesHelper
end

app/views/home_categories/_form.html.erb
<% if @category.errors.any? %>
	<div id="error_explanation">
		<%= t("general.form_error") %>
	</div>
<% end %>

<section class="content">
	<div class="row">
		<div class="col-md-6">
			<div class="box box-primary">
				<div class="box-header">
					<h3 class="box-title"><%= t("title.category") %></h3>
				</div>
				<%= form_for @category do |f| %>
					<div class="box-body">
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-file-text-o"></i>
								</div>
								<%= f.text_field :name, class: "form-control", placeholder: t("placeholder.name"), autofocus: true %>
								<%= error_tag @category, :name %>
							</div>
						</div>
					</div>
					<div class="box-footer">
						<%= f.submit button_name, class: "btn btn-primary" %>
	        </div>
				<% end %>
			</div>
		</div>
	</div>
</section>

app/views/home_categories/edit.html.erb
<%= render "form" %>

app/views/home_categories/index.html.erb
<section class="content">
	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title"><%= t("title.categories") %></h3>
					<div class="box-tools">
						<%= link_to t("link.registering"), new_home_category_path, class: "btn-register btn-default pull-right" %>
					</div>
				</div>
				<div class="box-body table-responsive no-padding">
					<table class="table table-striped">
						<tr>
							<th><%= t("table.name") %></th>
							<th colspan="2"></th>
						</tr>
						<% @categories.each do |category| %>
							<tr>
								<td><%= category.name %></td>
								<td><%= link_to "", edit_home_category_path(category), class: "fa fa-edit", title: t("link.edit") %></td>
								<td><%= link_to "", category, method: :delete, data: { confirm: t("flash_message.are_you_sure") }, class: "fa fa-trash-o", title: t("link.delete") %></td>
							</tr>
						<% end %>
					</table>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/home_categories/new.html.erb
<%= render "form" %>