config/routes.rb
Rails.application.routes.draw do
  LOCALES = /en|pt\-BR/

  scope "(:locale)", locale: LOCALES do
    get 'home/index'

    resources :home_categories
    resources :herba_categories

    resources :home_clients
    resources :herba_clients

    resources :herba_incomes
    resources :herba_items do
      member do
        post "confirm_delivery"
      end
    end

    resources :herba_products do
      member do
        post "add_item"
      end
    end

    resources :herba_profiles

    resources :herba_titles

    resources :home_transactions do
      collection do
        get "new_credit_card"
        post "create_credit_card"
        get "new_transfer"
        post "create_transfer"
      end
    end

    resources :herba_transactions

    if Rails.env.production?
      devise_for :users, :controllers => { :registrations => "registrations" } 
    else
      devise_for :users
    end
  end

  get "/:locale" => "home#index", locale: LOCALES
  root to: "home#index"

end

app/controllers/home_transactions_controller.rb
class HomeTransactionsController < ApplicationController
  before_action :authenticate_user!
  
	def index
    if params[:home_category_id].present?
      @transactions = HomeTransaction.includes(:home_category).where("home_category_id = ? and created_at <= ?", params[:home_category_id], Time.now.end_of_day).page(params[:page]).order(created_at: :desc)
    elsif params[:home_client_id].present?
      @transactions = HomeTransaction.includes(:home_category).where("created_at <= ? and home_client_id = ?", Time.now.end_of_day, 2).page(params[:page]).order(created_at: :desc)
    else
		  @transactions = HomeTransaction.includes(:home_category).where("created_at <= ? and home_client_id = ?", Time.now.end_of_day, 1).page(params[:page]).order(created_at: :desc)
    end
    @future_transactions = HomeTransaction.includes(:home_category).where("created_at > ? and created_at <= ? and home_client_id = ?", Time.now.end_of_day, Time.now.end_of_day + 1.month, 1).page(params[:page]).order(created_at: :desc)
	end

  def edit
    @transaction = HomeTransaction.find(params[:id])
  end

  def new
  	@transaction = HomeTransaction.new
  end

  def create
  	@transaction = HomeTransaction.new(transaction_params)

  	if @transaction.save
  		redirect_to new_home_transaction_path, notice: t("title.transaction") + t("flash_message.successfully_created")
  	else
  		render action: :new
  	end
  end

  def update
    @transaction = HomeTransaction.find(params[:id])

    if @transaction.update(transaction_params)
      redirect_to home_transactions_path, notice: t("title.transaction") + t("flash_message.successfully_updated")
    else
      render action: :edit
    end
  end

  def destroy
    @transaction = HomeTransaction.find(params[:id])
    @transaction.destroy
    redirect_to home_transactions_path, notice: t("title.transaction") + t("flash_message.successfully_deleted")
  end

  def new_credit_card
    @transaction = HomeTransaction.new
  end

  def create_credit_card
    parcel = params[:parcel].to_i
    value = params[:home_transaction][:value].to_f/parcel

    parcel.times do |i|
      transaction = HomeTransaction.new
      transaction.value = value
      transaction.home_client_id = params[:home_transaction][:home_client_id]
      transaction.home_category_id = params[:home_transaction][:home_category_id]
      transaction.mode = "debit"
      transaction.description = "#{i+1}/#{parcel} #{params[:home_transaction][:description]}"
      transaction.created_at = (Date.today.beginning_of_month + 9.days) + (i + 1).month
      transaction.save
    end
    redirect_to new_credit_card_home_transactions_path, notice: t("title.transaction") + t("flash_message.successfully_created")
  end

  def new_transfer
    @transaction = HomeTransaction.new
  end

  def create_transfer
    transaction = HomeTransaction.new
    transaction.value = params[:home_transaction][:value]
    transaction.home_client_id = params[:from_client_id]
    transaction.home_category_id = 10
    transaction.mode = "debit"
    transaction.description = "Transferência"
    transaction.save

    transaction = HomeTransaction.new
    transaction.value = params[:home_transaction][:value]
    transaction.home_client_id = params[:to_client_id]
    transaction.home_category_id = 11
    transaction.mode = "credit"
    transaction.description = "Akio"
    transaction.save
    redirect_to home_transactions_path, notice: t("title.transaction") + t("flash_message.successfully_created")
  end

  private
  def transaction_params
  	params.require(:home_transaction).permit(:home_client_id, :home_category_id, :value, :profit, :mode, :description)
  end
end

app/helpers/home_transactions_helper.rb
module HomeTransactionsHelper
	def get_home_categories
		HomeCategory.all.order(:name)
	end

	def get_home_clients
		HomeClient.all.order(:name)
	end
end

app/views/home_transactions/_form.html.erb
<% if @transaction.errors.any? %>
	<div id="error_explanation">
		<%= t("general.form_error") %>
	</div>
<% end %>
<section class="content">
	<div class="row">
		<div class="col-md-6">
			<div class="box box-primary">
				<div class="box-header">
					<h3 class="box-title"><%= t("title.transaction") %></h3>
				</div>
				<%= form_for @transaction do |f| %>
					<div class="box-body">
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-money"></i>
								</div>
								<%= f.text_field :value, class: "form-control", placeholder: t("placeholder.money_example"), autofocus: true %>
								<%= error_tag @transaction, :value %>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-caret-square-o-down"></i>
								</div>
								<%= f.select :home_client_id, options_from_collection_for_select(get_home_clients, "id", "name", @transaction.home_client_id), {}, class: "form-control" %>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-caret-square-o-down"></i>
								</div>
								<%= f.select :home_category_id, options_from_collection_for_select(get_home_categories, "id", "name", @transaction.home_category_id), {}, class: "form-control" %>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-caret-square-o-down"></i>
								</div>
								<%= f.select :mode, options_for_select([["Débito", "debit"], ["Crédito", "credit"], ["Renda", "income"], ["Reembolso", "repayment"]], @transaction.mode), {}, class: "form-control" %>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-file-text-o"></i>
								</div>
								<%= f.text_field :description, class: "form-control", placeholder: t("placeholder.description") %>
								<%= error_tag @transaction, :description %>
							</div>
						</div>
					</div>
					<div class="box-footer">
						<%= f.submit button_name, class: "btn btn-primary" %>
	        </div>
				<% end %>
			</div>
		</div>
	</div>
</section>

app/views/home_transactions/edit.html.erb
<%= render "form" %>

app/views/home_transactions/index.html.erb
<section class="content">
	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title"><%= t("title.transactions") %></h3>
					<div class="box-tools">
						<%= link_to t("link.registering"), new_home_transaction_path, class: "btn-register btn-default pull-right" %>
						<div class="input-group-table">
							<%= form_tag home_transactions_path, method: :get do %>
								<div class="input-group-btn-table">
	              	<%= button_tag "", class: "btn btn-sm btn-default" do %>
	              		<i class="fa fa-search"></i>
	              	<% end%>
	              </div>
								<%= select_tag :home_category_id, options_from_collection_for_select(get_home_categories, "id", "name", params[:home_category_id]), :include_blank => true, class: "form-control-table pull-right" %>
								<%= select_tag :home_client_id, options_for_select([["", ""], ["Akio", 2]], params[:home_client_id]), class: "form-control-table pull-right" %>
							<% end %>
            </div>
					</div>
				</div>
				<div class="box-body table-responsive no-padding">
					<table class="table table-striped">
						<tr>
							<th><%= t("table.date") %></th>
							<th><%= t("table.category") %></th>
							<th><%= t("table.mode") %></th>
							<th><%= t("table.value") %></th>
							<th><%= t("table.description") %></th>
							<th colspan="2"></th>
						</tr>
						<% @transactions.each do |transaction| %>
							<tr>
								<td><%= format_date(transaction.created_at) %></td>
								<td><%= transaction.home_category.name %></td>
								<td><%= transaction.translate_mode %></td>
								<td><%= format_money(transaction.value) %></td>
								<td><%= transaction.description %></td>
								<td><%= link_to "", edit_home_transaction_path(transaction), class: "fa fa-edit", title: t("link.edit") %></td>
								<td><%= link_to "", transaction, method: :delete, data: { confirm: t("flash_message.are_you_sure") }, class: "fa fa-trash-o", title: t("link.delete") %></td>
							</tr>
						<% end %>
					</table>
					<div class="box-footer clearfix">
						<div class="pagination pagination-sm no-margin pull-right">
							<%= will_paginate @transactions %>
						</div>
					</div>
				</div>
				<div class="box-header">
					<h3 class="box-title"><%= t("title.future_transactions") %></h3>
				</div>
				<div class="box-body table-responsive no-padding">
					<table class="table table-striped">
						<tr>
							<th><%= t("table.date") %></th>
							<th><%= t("table.category") %></th>
							<th><%= t("table.mode") %></th>
							<th><%= t("table.value") %></th>
							<th><%= t("table.description") %></th>
							<th colspan="2"></th>
						</tr>
						<% @future_transactions.each do |transaction| %>
							<tr>
								<td><%= format_date(transaction.created_at) %></td>
								<td><%= transaction.home_category.name %></td>
								<td><%= transaction.translate_mode %></td>
								<td><%= format_money(transaction.value) %></td>
								<td><%= transaction.description %></td>
								<td><%= link_to "", edit_home_transaction_path(transaction), class: "fa fa-edit", title: t("link.edit") %></td>
								<td><%= link_to "", transaction, method: :delete, data: { confirm: t("flash_message.are_you_sure") }, class: "fa fa-trash-o", title: t("link.delete") %></td>
							</tr>
						<% end %>
					</table>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/home_transactions/new.html.erb
<%= render "form" %>

app/views/home_transactions/new_credit_card.html.erb
<% if @transaction.errors.any? %>
	<div id="error_explanation">
		<%= t("general.form_error") %>
	</div>
<% end %>
<section class="content">
	<div class="row">
		<div class="col-md-6">
			<div class="box box-primary">
				<div class="box-header">
					<h3 class="box-title"><%= t("title.credit_card_transaction") %></h3>
				</div>
				<%= form_for(@transaction, url: create_credit_card_home_transactions_path) do |f| %>
					<div class="box-body">
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-money"></i>
								</div>
								<%= f.text_field :value, class: "form-control", placeholder: t("placeholder.money_example"), autofocus: true %>
								<%= error_tag @transaction, :value %>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-caret-square-o-down"></i>
								</div>
								<%= f.select :home_client_id, options_from_collection_for_select(get_home_clients, "id", "name", @transaction.home_client_id), {}, class: "form-control" %>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-caret-square-o-down"></i>
								</div>
								<%= f.select :home_category_id, options_from_collection_for_select(get_home_categories, "id", "name", @transaction.home_category_id), {}, class: "form-control" %>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-file-text-o"></i>
								</div>
								<%= f.text_field :description, class: "form-control", placeholder: t("placeholder.description") %>
								<%= error_tag @transaction, :description %>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-caret-square-o-down"></i>
								</div>
								<%= select_tag :parcel, options_for_select(["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]), class: "form-control" %>
							</div>
						</div>
					</div>
					<div class="box-footer">
						<%= f.submit button_name, class: "btn btn-primary" %>
	        </div>
				<% end %>
			</div>
		</div>
	</div>
</section>

app/views/home_transactions/new_transfer.html.erb
<% if @transaction.errors.any? %>
	<div id="error_explanation">
		<%= t("general.form_error") %>
	</div>
<% end %>
<section class="content">
	<div class="row">
		<div class="col-md-6">
			<div class="box box-primary">
				<div class="box-header">
					<h3 class="box-title"><%= t("title.credit_card_transaction") %></h3>
				</div>
				<%= form_for(@transaction, url: create_transfer_home_transactions_path) do |f| %>
					<div class="box-body">
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-money"></i>
								</div>
								<%= f.text_field :value, class: "form-control", placeholder: t("placeholder.money_example"), autofocus: true %>
								<%= error_tag @transaction, :value %>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									De
								</div>
								<%= select_tag :from_client_id, options_from_collection_for_select(get_home_clients, "id", "name"), class: "form-control" %>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									Para
								</div>
								<%= select_tag :to_client_id, options_from_collection_for_select(get_home_clients, "id", "name"), class: "form-control" %>
							</div>
						</div>
					</div>
					<div class="box-footer">
						<%= f.submit button_name, class: "btn btn-primary" %>
	        </div>
				<% end %>
			</div>
		</div>
	</div>
</section>